# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='appreoved_comment',
            new_name='approved_comment',
        ),
    ]
